---
- set_fact: rdbms=mariadb

- set_fact: rdbms=mysql
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int < 14

# fix once https://github.com/ansible/ansible/pull/17782
- set_fact: rdbms_root_pw="{{ lookup('password', '~/' + rdbms + '_root_password_' + ansible_fqdn + ' length=15') }}"
  no_log: True

- include_vars: "{{ item }}"
  with_first_found:
    - "sys_{{ ansible_distribution }}_{{ rdbms }}.yml"
    - "sys_{{ ansible_os_family }}_{{ rdbms }}.yml"

- name: Install database packages
  package:
    name: "{{ item }}"
    state: installed
  with_items: "{{ rdbms_packages }}"

- name: Deploy mysql configuration
  template:
    src: my.server.cnf
    dest: /etc/my.cnf
  notify: restart rdbms
  when: rdbms == 'mysql'

- name: "Start the {{ rdbms_service }} service"
  service:
    name: "{{ rdbms_service }}"
    enabled: yes
    state: started

- name: Set database admin password
  mysql_user:
    name: root
    password: "{{ rdbms_root_pw }}"

- name: Deploy the client configuration
  template:
    src: my.client.cnf
    dest: /root/.my.cnf
    mode: 600
    owner: root
    group: root
  no_log: True

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Disallow root login remotely
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1', '10.0.0.30')
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False
  ignore_errors: True

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False
