---
- name: Create MySQL database for thirtybees
  mysql_db: name=thirtybees state=present

- name: Create MySQL user for thirtybees
  mysql_user: name=thirtybees password=thirtybees priv=*.*:ALL state=present

- name: Clone thirty bees
  git: repo=https://github.com/thirtybees/thirtybees.git
       dest=/vagrant/thirtybees
       depth=1
       recursive=yes
       version=1.0.1
       update=no
  become: true
  become_user: "{{ www_user }}"

- name: Install thirtybees project dependencies
  shell: cd /vagrant/thirtybees-standard && COMPOSER_PROCESS_TIMEOUT={{composer_process_timeout}} composer install
  become: true
  become_user: "{{ www_user }}"

- name: Copy across new php-fpm pool config for thirtybees
  template:
    src=php-fpm.conf.j2
    dest=/etc/php/{{ php_version }}/fpm/pool.d/thirtybees.conf
  notify:
    - restart php-fpm

- name: Copy across new virtual host for thirtybees
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/sites-available/thirtybees.conf
  notify:
    - restart nginx

- name: Enable new vagrant virtual host for thirtybees
  file:
    src=/etc/nginx/sites-available/thirtybees.conf
    dest=/etc/nginx/sites-enabled/thirtybees.conf
    state=link
  notify:
    - restart nginx
